import Head from 'next/head';
import fhome from '../public/assets/fhome.svg';
import Footer from '../components/footer/Footer';
import NewNav from '../components/navbar/NewNav';
import Link from 'next/link';
// import {signIn, signOut, useSession} from 'next-auth/client';

export default function Home() {
  // const [session, loading] = useSession();

  // useEffect(() =>{
  //   // getUser();
  // }, []);

  
  return (
    <div>
      <Head>
        <title>Starmint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NewNav/>
      <main className=' sm:h-screen h-[100%] flex flex-col  text-[#707A83]'>
        <div className='px-8 md:px-20 lg:px-32 xl:px-40 2xl:px-52 flex pt-16 items-center grow'>
          <div className='flex flex-col w-full h-full md:flex-row  justify-center relative  gap-8'>
            <div className='flex w-auto md:w-[50%]  flex-col justify-center'>
              <h1 className='text-6xl xl:text-8xl 2xl:text-[8rem] font-bold'>Create. <br /> Share. <br /> Sell.</h1>
              <p className='text-3xl xl:text-4xl py-6 '>Create NTFs for free and build unique relationships with your community.</p>
              <Link href="/create">
                <button class="bg-transparent hover:bg-gray-500 text-gray-700 text-gray font-semibold hover:text-black py-2 px-4 border border-gray-500 hover:border-transparent rounded">
                  Create now
                </button>
              </Link>
              {/* {!session ? 
                <>
                  <p>Not sign in</p> <br />
                </> : 
                <></>
              } */}
            </div>
            <div className='flex justify-center md:justify-end w-auto md:w-[50%] relative'>
              <img
                src="/assets/fhome.svg"
                alt="Picture of the author"
                width={500}
                height={500}
              />
            </div>
          </div>
        </div>
        <Footer/>
      </main>
      
    </div>
  )
}
